services:
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#      # 빌드 최적화 옵션
#      args:
#        BUILDKIT_INLINE_CACHE: 1
#    container_name: spring-app
#    ports:
#      - "8080:8080"
#    depends_on:
#      - mysql
#      - redis
#    env_file:
#      - .env
#    networks:
#      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

  redis:
    image: redis:7.0
    container_name: redis
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

volumes:
  mysql-data:
    driver: local
  redis-data:

networks:
  backend:
